<a href="https://colab.research.google.com/github/Shreyaa-J/NumPy-Journey/blob/main/NumPy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#Basic Array Creation

In [ ]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
a=[1,2,3.5,"Hii"]
a

[1, 2, 3.5, 'Hii']

In [ ]:
#Converting above list to np
np.array(a)

array(['1', '2', '3.5', 'Hii'], dtype='<U32')

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Creation of matrix using numpy

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Array Generating Function

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1=np.arange(2,10,2)
arr1

array([2, 4, 6, 8])

In [4]:
arr=np.zeros(3)
arr

array([0., 0., 0.])

In [5]:
#To generate matrix
arr=np.zeros((4,8))
arr


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [8]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
#linespace- Returns evenly spaced no. over a specified interval
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [13]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [14]:
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#Random Genration Function

In [15]:
np.random.rand(10)

array([0.52769576, 0.74230496, 0.64558942, 0.32700666, 0.04619628,
       0.54720887, 0.67720326, 0.06226467, 0.03023783, 0.46982602])