<a href="https://colab.research.google.com/github/Shreyaa-J/NumPy-Journey/blob/main/NumPy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Basic Array Creation

In [3]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
a=[1,2,3.5,"Hii"]
a

[1, 2, 3.5, 'Hii']

In [5]:
#Converting above list to np
np.array(a)

array(['1', '2', '3.5', 'Hii'], dtype='<U32')

In [6]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Creation of matrix using numpy

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Array Generating Function

In [10]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr1=np.arange(2,10,2)
arr1

array([2, 4, 6, 8])